### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by KarlAuston** [ssuda1/guncontrol_public_opinion#2]
Hi, I found that the data of the dataset (twtgun3.24.10.txt) end  at 'created_at': 'Sun Mar 25 00:55:08 +0000 2018'.

Could you please give me some more data about 3.25&3.26？

Thank you very much.

**Comment by ssuda1** [comment]
Sorry but I'm not distributing the data at this moment. I put partial data from 3/24 on the repository to showcase the type of the data I collected. Thank you.
